xeroc/python-graphenelib

- MANIFEST.in
- grapheneapi/grapheneapi.py
here are 2 small fixes for small issues I had:
- there was a bug when the rpc function would return something else than a list and a bool (an int, for example)
- "python setup.py sdist" didn't produce an installable package because the readme.md file was missing from the build
btw, I've started using your lib to provide support for graphene clients in my tools and I like it a lot, it's very nice! It's been really helpful to understand how graphene works with respect to the previous 0.9 design. Thanks!
> A few minor fixes for small issues I encountered

- scripts/switch-keys/config-example.py
- scripts/switch-keys/example-config.ini
- scripts/switch-keys/switch.py
script will now launch witness node and cli wallet, unlock wallet, watch for missed blocks and switch between public keys, switch to emergency keys if all primary keys miss blocks twice, close and relaunch with --replay-blockchain if witness participation falls below 50% or witness node or script crashes.  Will close and relaunch with --resync-blockchain if three attempts at --replay-blockchain are unable to fix problem.  Requires lots of config.py parameters.
> Lots of bug fixes

- grapheneapi/graphenewsprotocol.py
Without this, notices are dispatched for all objects to the None object even if no account is subscribed
> fix: no notices if no account is subscribed

- grapheneapi/graphenews.py
- grapheneapi/graphenewsrpc.py
Added the possibility to provide GrapheneWebsocketRPC() and GrapheneWebsocket(GrapheneWebsocketRPC) with a list of witness urls instead of one.
Automatically switches over to the next node in the list when the connection with a full node is lost.
> Added Websocket(RPC) failover

- graphenebase/ecdsa.py
- tests/test_ecdsa.py
* unit test for ecdsa fixed
The new implementation is 166.98 % (sign) and 229.39 % (verify) faster than before, when secp256k1 is not installed!
> Improve sign and verify speed by 200% if secp256k1 is not installed

- graphenebase/account.py
NOTE: I'm not 100% sure those belong to Graphene, I've taken them from BitShares.
I'll open an alternative pull request there, if that's more appropriate.
> Add additional crypto methods to PrivateKey.

- graphenebase/account.py
- graphenebase/ecdsa.py
Note: `tweak_add` will NOT work without secp256k1. We shall add pure-python implementation for such cases.
> Add additional crypto methods to PublicKey.

- graphenebase/account.py
- tests/test_account.py
This is the same as `get_private` method, but without any sequence number. It's used for generating private keys for Blind accounts on BitShares network.
> Add get_blind_private method to BrainKey.

- graphenebase/account.py
- graphenebase/ecdsa.py
- requirements-test.txt
- tests/test_account.py
I've noticed it's commented out. 
(I don't remember if `tweakmulPubkey` is actually used anywhere, so I've left it out for now.)
> Restore tweakaddPubkey method and related unit tests.

- graphenebase/account.py
- tests/test_crypto.py
I've randomly encounted a privkey + offset combo that provide a 63-byte secret value (instead of expected 64). Looking at the code, there's nothing to guarantee secp values will be large enough, so some padding is necessary.
> Add zero padding to derived privkeys.

- graphenecommon/blockchain.py
Non-bitshares networks can have different way of obtaining block
interval, this change easies overriding of it.
> Move getting of block interval into separate method

- graphenecommon/amount.py
When performing math operations (or comparisons) between Amounts, no
need to do strict full-dict comparison of Assets, it's enough to make sure
asset ids are the same. An asset param may change, thus screwing a
comparison:
```python
a = Amount('10 CNY')
b = Amount('10 CNY')
a['asset']['options']['core_exchange_rate']['base']['amount'] += 1
a == b  # False
```
Closes: #101
> Impove Amount math actions

- graphenestorage/__init__.py
- graphenestorage/sqlite.py
Each time sqlite-related fetch/execute is performed, the code similar to
```
connection = sqlite3.connect(self.sqlite_file)
cursor = connection.cursor()
cursor.execute(*query)
```
is executed.
It would be beneficial to factor those out, to avoid some code duplication, but more importantly, to allow one to redefine those methods (without messing around the actual `keys()` or `items()` functions).
I do, in fact, override those methods in the python-qt wallet implementation of python-graphenelib, to provide additional safeguards (and thread-safe locking), as sqlite on some platforms is compiled in non-thread-safe mode.
Note on implementation: this adds yet another class to the sqlite-storage stack. Arguably, SQLiteFile class could've handled this, but I've found it's nice to separate the …
> Factor out common sqlite operations into a separate class.

- graphenecommon/block.py
block does not contain an id and thus identifier gets overwritten
> Keep block identifier

- grapheneapi/aio/api.py
- grapheneapi/api.py
__getattr__() in grapheneapi.aio.Api wasn't defined, so it used regular
__getattr__(), which didn't contains `await func()` call, so it just
returned a coroutine without actually calling it, so all exception
handling didn't worked here. Thus, connection-related errors (broken
connection) weren't handled.
> Fix RPC method calling in aio version

- requirements.txt
0.56.0 works, though 0.57.0 has some bugfixes. Hope that upstream will
not broke backward compatibility before major version bump.
> Allow wider websocket-client versions

- graphenecommon/aio/transactionbuilder.py
- graphenecommon/transactionbuilder.py
Problem: any high-level method as bitshares.transfer() instantiates
op = operations.Transfer(), then self.json() inside TransactionBuilder
makes OrderedDict to dict, and then Signed_Transaction class have to
reconstruct all operations via kwargs["operations"] = Array([opklass(a)
for a in ops]). This way breaks possible use of Variant type encoding
(may be used by other chains).
> Avoid double instantiation of operations

- graphenecommon/aio/transactionbuilder.py
- graphenecommon/transactionbuilder.py
When calling broadcast() on proposal, it proxied to self.parent, which
performing self.sign() only if not signed already. Proposal uses main
TransactionBuilder instance by default, which may contain signature from
previously broadcasted trx, thus failing proposal broadcast with
"Missing Active Authority".
> Always sign() proposal trx before broadcasting

- grapheneapi/websocket.py
See https://github.com/Codaone/DEXBot/issues/447.
The client may occasionally hang on `recv()` when fetching data from an API node, this can be simulated using the iptables rule `iptables -A INPUT -s x.x.x.x -p tcp --sport xxx -j DROP`. Setting a timeout can fix it.
The reason why it may hang on `recv()` is still unknown, maybe it's an OS bug.
> Set a timeout when connecting to websocket server

- graphenecommon/blockchainobject.py
On some race conditions, a blockchain object list may call twice store_items with the same list loaded, thus creating duplicates in the cache. 
This fix adds a duplicate check to the cache
> fix: store items duplicate check
